version: '3.8'

services:
  table-chair:
    image: mamadaliyevmuhammadyusuf/tablechair:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

